### ISSUE TITLE
DNS seed に接続できない場合の対策

### ISSUE THREAD

**Issue by tomotomo9696** [dkwzjw/ringo#4]
[Askmona](https://askmona.org/9784) でも議論されていますが、
全ての DNS seed に接続できない場合、（かつ peers.dat と addnode の設定がない場合）
ネットワークへの接続が確立できません。

DNS seed が実際には接続できない場合でも、一つでも名前解決ができればエラーとみなされず
pnSeed を使うことはなさそうです。
理想としては DNS seed を増やすことですが、いくつか改善案を提示させていただきます。

1. -dnsseed オプションをデフォルトで無効にします。これにより pnSeed が使用されます。
2. 名前解決された DNS seed が一定数以下の場合、pnSeed も使用するように変更します。
3. ThreadDNSAddressSeed において、接続可否のチェックを追加します。
4. 一定回数接続失敗したノードを、リストから外すようにします。

**Comment by dkwzjw** [comment]
そうですねー
いっそDNSseedナシにしちゃうのがいいのかも
いただいたホストはつながらない対策のaddnodeとして利用させてもらおうかなぁ
この辺を公式で案内しておく感じで

**Comment by tomotomo9696** [comment]
そうですね、それならすぐに対応できますね。

2 の peers.dat + DNSSeed が一定数以下で pnSeed を使う場合以下を変えれば良さそうですかね。
https://github.com/dkwzjw/ringo/blob/04261de5c2d8e5c44867353cf4d8f369c926c232/src/net.cpp#L1381

**Comment by dkwzjw** [comment]
提案ありがとう！
あとはpeers.datをbootstrapみたいに定期的に更新するのもいいかも
結局pnSeedの情報が古くなると繋がるまで時間かかっちゃいますから

**Comment by tomotomo9696** [comment]
なるほど、その方が bootstrap に依存するよりかは良さそうですね。
それと、既に無用の長物と化してる IRCSeed ですが、今チャットで使ってる IRC を使って復活させるのは難しいですかね？

**Comment by dkwzjw** [comment]
特定のものに依存するのを増やすと後で大変そうかもです
